# docker-compose.yml
services:
  app:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_ADDRESS=redis:6379  
      - DB_PASSWORD=
      - API_QUOTA=10
      - DOMAIN=localhost:3000
    depends_on:
      - redis
    networks:
      - url-shortener

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6380:6379" 
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - url-shortener

networks:
  url-shortener:
    driver: bridge

volumes:
  redis-data: