FROM golang:1.22-alpine

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN go build -o main .

# Optional: Use a smaller base image for the final stage
FROM alpine:latest
WORKDIR /app
COPY --from=0 /app/main .
CMD ["./main"]